### ISSUE TITLE
problems with "grunt plugin watch"

### ISSUE THREAD

**Issue by mgrauer** [Kitware/minerva#208] opened 2015-11-18 22:12 UTC
(1)

If I run  `grunt plugin watch --verbose` I can see which files are being watched, and it is a number in the thousands, mostly brought in by the [plugin-minerva-build-geojs](https://github.com/Kitware/minerva/blob/c7b82591415c0ee991347ba1b1762e47bf22421e/Gruntfile.js#L195-L198) watch.  This should be a more specific list I'm guessing.

(2)

If I comment out the `watch` section from Minerva's Gruntfile, I see these files watched, so I'm guessing they are set in Girder's plugin watch, but this list doesn't seem desirable.

>Watching plugins/minerva/package.json for changes.
Watching plugins/minerva/.git for changes.
Watching plugins/minerva/analyses for changes.
Watching plugins/minerva/data_services for changes.
Watching plugins/minerva/docs for changes.
Watching plugins/minerva/node_modules for changes.
Watching plugins/minerva/plugin_tests for changes.
Watching plugins/minerva/server for changes.
Watching plugins/minerva/utility for changes.
Watching plugins/minerva/web_client for changes.
Watching plugins/minerva/web_external for changes.

(3)

Our jade, stylus and javascript files are not being watched.

If I change [plugin-minerva-jade-external](https://github.com/Kitware/minerva/blob/c7b82591415c0ee991347ba1b1762e47bf22421e/Gruntfile.js#L183-L186) watch from

    files: _.pluck(grunt.config.get('jade.minerva.files'), 'src'),

to 

    files: ['<%= plugin.minerva.external %>/templates/**/*.jade']

this will correctly watch the jade files.  Unfortunately this now duplicates the listing of the jade files instead of referring to some earlier set variable from the grunt config, and that is much worse in the case of the [uglify task's files](https://github.com/Kitware/minerva/blob/c7b82591415c0ee991347ba1b1762e47bf22421e/Gruntfile.js#L85-L121).

ping @jbeezley for the best way to fix this.

**Comment by jbeezley** [comment] 2015-11-19 14:58
@mgrauer Thanks for the information.  I'll take a look at it once I get a couple of other things off my plate.

**Comment by mgrauer** [comment] 2015-11-19 14:59
No rush for Minerva.

I wanted to bring it to your attention in case you thought it needed to be addressed before the next Girder minor release.

**Comment by jbeezley** [comment] 2015-11-19 15:04
Good point.  I'll create an issue over there.  The "watch" task is kind of esoteric , so I don't suspect that this will be a blocker for the release.

**Comment by jbeezley** [comment] 2015-11-24 22:08
The issue for the main plugin targets is addressed in https://github.com/girder/girder/pull/1117.  I can reproduce the output of `grunt --verbose watch`.  It seems to be some `grunt` or `grunt-contrib-watch` bug.  There is nothing wrong with the config object and nothing is executed when you touch the watched directories (or anything inside).  I'll get to fixing the Minerva specific parts later.

**Closed** 2015-12-03 17:04 UTC
